### PR TITLE
#172574603 Change social media redirect.

### PR DESCRIPTION
**Pull request by Niyonsengaeric**
#### What does this PR do?
- Redirect the user to the fronted page after successful login using Google or Facebook.
#### Description of Task to be completed?
- change the redirect link.
- pass data to the fronted URL as a query string.
#### How should this be manually tested?
- N/A
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- N/A
#### Screenshots (if appropriate)
- N/A

### CODE REVIEW

**Review by EugeneMunya — APPROVED** [review]

**Comment by T2Wil** [comment]
Morning @Niyonsengaeric , 
please provide a screenshot of the redirect URL in action (on front-end).

**Comment by Niyonsengaeric** [comment]
@T2Wil  I think the screenshot is not needed because here it redirects to the home page which is not yet implemented.

**Comment by T2Wil** [comment]
> @T2Wil I think the screenshot is not needed because here it redirects to the home page which is not yet implemented.

As I have seen, you are transferring data through URL path, I need to see how those data on the redirecting URL are displayed: to know whether are encrypted or not.....
You don't have to implement the page.

**Comment by Niyonsengaeric** [comment]
@T2Wil  here I don't really know what you want to mean but the data in the UR are not displayed instead we save some data we need in the fronted unless if you want to talk about the frontend code 
Screen Shot 2020-04-29 at 09 32 36

 May I see this location.search?
image

**Review by T2Wil — APPROVED** [review]

**Review by kagabof — APPROVED** [review]
Well done.

**Pull request merged**
